### PR TITLE
Add 'node_id' attribute to core modules

### PR DESCRIPTION
**Pull request by stephdl**
This pull request adds the 'node_id' attribute to the core modules in the codebase. The 'node_id' attribute is used to identify the node where the module is installed. This change ensures that the 'node_id' is included in the core module list and is displayed in the software center UI.

https://github.com/NethServer/dev/issues/6989

image
image
image
image

### CODE REVIEW

**Review by andre8244 — COMMENTED** [review]
Is it possible to add node label, if present? In NS8 UI, a node is usually named:
- "My first node (Node 1)" if node label is present
- "Node 1" if node label is not present

If this change makes sense, I also suggest to rename "Node ID" column to to "Node"

**Comment by stephdl** [comment]
do you mean to display in the column instead of `1` rename to `Node 1`

**Comment by andre8244** [comment]
> do you mean to display in the column instead of `1` rename to `Node 1` @andre8244 ?

Yes, or display "My node (Node 1)" if the node has a label "My node" set

**Comment by andre8244** [comment]
> > do you mean to display in the column instead of `1` rename to `Node 1` @andre8244 ?
> 
> Yes, or display "My node (Node 1)" if the node has a label "My node" set

You can use [getNodeLabel()](https://github.com/NethServer/ns8-ui-lib/blob/main/src/lib-mixins/util.js#L287) function from ns8-ui-lib

**Comment by stephdl** [comment]
I need to share with @DavidePrincipi, I am not sure it is in the scope, the goal is to sort by node ID, and any verbose label could break it
What do you think davidep

**Comment by andre8244** [comment]
> I need to share with @DavidePrincipi, I am not sure it is in the scope, the goal is to sort by node ID, and any verbose label could break it What do you think davidep

NsDataTable component supports custom sorting with `customSortTable` prop, you can find an example here: https://github.com/NethServer/ns8-mail/blob/main/ui/src/components/mailboxes/UserMailboxes.vue#L15

**Review by andre8244 — APPROVED** [review]

**Pull request merged**
